In [11]:
import sys
import os
sys.path.append(os.path.abspath("/app"))

In [12]:
import pandas as pd
import os

df = pd.read_csv("../data/cell2info.csv")

In [13]:
df

,CellID,Name,Tissue,Organism,TaxonomyID,Synonyms
0,1,HEL,blood,Homo sapiens (human),9606.0,Hel|GM06141|GM06141B|Human ErythroLeukemia
1,2,HL-60,blood,Homo sapiens (human),9606.0,HL 60|HL.60|HL60|Human Leukemia-60
2,3,HMC-1,blood,Homo sapiens (human),9606.0,HMC1
3,4,K-562,pleural effusion,Homo sapiens (human),9606.0,K562|K.562|K 562|KO|GM05372|GM05372E
4,5,NB4,bone marrow,Homo sapiens (human),9606.0,NB-4|NB.4
...,...,...,...,...,...,...
161654,161711,SK-007,Haematopoietic and lymphoid myeloma,Homo sapiens (human),9606.0,NaN
161655,161712,NIH-3T3/LISN,Fibroblast,Mus musculus (house mouse),10090.0,NaN
161656,161713,KHOS,Osteosarcoma,Homo sapiens (human),9606.0,NaN
161657,161714,MOLM-13-QR,Adult acute myeloid leukemia,Homo sapiens (human),9606.0,NaN
161658,161715,RN2,Mouse leukemia,Mus musculus (house mouse),10090.0,NaN

In [14]:
primary_key = "CellID"

not_primary_columns = [c for c in df.columns if c != primary_key]
not_primary_columns

['Name', 'Tissue', 'Organism', 'TaxonomyID', 'Synonyms']

In [15]:
for i, c1 in enumerate(not_primary_columns):
    for j, c2 in enumerate(not_primary_columns):
        if i != j:
            key = df[c1].dropna().unique()
            temp_df = df[[c1,c2]]
            print(f"# keys in {c1}: {key.shape[0]}")
            temp_df = temp_df[temp_df[c1].isin(key)]
            temp_df = temp_df.drop_duplicates()
            print(temp_df.shape[0])
            print(f"# Nan in {c1}: {temp_df[c1].isna().sum()}")
            print(f"# Nan in {c2}: {temp_df[c2].isna().sum()}")
            print(temp_df)
            print()

# keys in Name: 161576
161600
# Nan in Name: 0
# Nan in Tissue: 27155
                Name                               Tissue
0                HEL                                blood
1              HL-60                                blood
2              HMC-1                                blood
3              K-562                     pleural effusion
4                NB4                          bone marrow
...              ...                                  ...
161654        SK-007  Haematopoietic and lymphoid myeloma
161655  NIH-3T3/LISN                           Fibroblast
161656          KHOS                         Osteosarcoma
161657    MOLM-13-QR         Adult acute myeloid leukemia
161658           RN2                       Mouse leukemia

[161600 rows x 2 columns]

# keys in Name: 161576
161646
# Nan in Name: 0
# Nan in Organism: 1590
                Name                    Organism
0                HEL        Homo sapiens (human)
1              HL-60        Homo sapiens (human)
2              HMC-1        Homo sapiens (human)
3              K-562        Homo sapiens (human)
4                NB4        Homo sapiens (human)
...              ...                         ...
161654        SK-007        Homo sapiens (human)
161655  NIH-3T3/LISN  Mus musculus (house mouse)
161656          KHOS        Homo sapiens (human)
161657    MOLM-13-QR        Homo sapiens (human)
161658           RN2  Mus musculus (house mouse)

[161646 rows x 2 columns]

# keys in Name: 161576
161646
# Nan in Name: 0
# Nan in TaxonomyID: 1590
                Name  TaxonomyID
0                HEL      9606.0
1              HL-60      9606.0
2              HMC-1      9606.0
3              K-562      9606.0
4                NB4      9606.0
...              ...         ...
161654        SK-007      9606.0
161655  NIH-3T3/LISN     10090.0
161656          KHOS      9606.0
161657    MOLM-13-QR      9606.0
161658           RN2     10090.0

[161646 rows x 2 columns]

# keys in Name: 161576
161587
# Nan in Name: 0
# Nan in Synonyms: 81663
                Name                                    Synonyms
0                HEL  Hel|GM06141|GM06141B|Human ErythroLeukemia
1              HL-60          HL 60|HL.60|HL60|Human Leukemia-60
2              HMC-1                                        HMC1
3              K-562        K562|K.562|K 562|KO|GM05372|GM05372E
4                NB4                                   NB-4|NB.4
...              ...                                         ...
161654        SK-007                                         NaN
161655  NIH-3T3/LISN                                         NaN
161656          KHOS                                         NaN
161657    MOLM-13-QR                                         NaN
161658           RN2                                         NaN

[161587 rows x 2 columns]

# keys in Tissue: 962
134446
# Nan in Tissue: 0
# Nan in Name: 1
                                     Tissue          Name
0                                     blood           HEL
1                                     blood         HL-60
2                                     blood         HMC-1
3                          pleural effusion         K-562
4                               bone marrow           NB4
...                                     ...           ...
161654  Haematopoietic and lymphoid myeloma        SK-007
161655                           Fibroblast  NIH-3T3/LISN
161656                         Osteosarcoma          KHOS
161657         Adult acute myeloid leukemia    MOLM-13-QR
161658                       Mouse leukemia           RN2

[134446 rows x 2 columns]

# keys in Tissue: 962
3052
# Nan in Tissue: 0
# Nan in Organism: 53
                                     Tissue                    Organism
0                                     blood        Homo sapiens (human)
3                          pleural effusion        Homo sapiens (human)
4                               bone marrow        Homo sapiens (human)
17                               cerebellum        Homo sapiens (human)
19                                    brain        Homo sapiens (human)
...                                     ...                         ...
161650         Adult acute myeloid leukemia        Homo sapiens (human)
161654  Haematopoietic and lymphoid myeloma        Homo sapiens (human)
161655                           Fibroblast  Mus musculus (house mouse)
161656                         Osteosarcoma        Homo sapiens (human)
161658                       Mouse leukemia  Mus musculus (house mouse)

[3052 rows x 2 columns]

# keys in Tissue: 962
3049
# Nan in Tissue: 0
# Nan in TaxonomyID: 53
                                     Tissue  TaxonomyID
0                                     blood      9606.0
3                          pleural effusion      9606.0
4                               bone marrow      9606.0
17                               cerebellum      9606.0
19                                    brain      9606.0
...                                     ...         ...
161650         Adult acute myeloid leukemia      9606.0
161654  Haematopoietic and lymphoid myeloma      9606.0
161655                           Fibroblast     10090.0
161656                         Osteosarcoma      9606.0
161658                       Mouse leukemia     10090.0

[3049 rows x 2 columns]

# keys in Tissue: 962
68068
# Nan in Tissue: 0
# Nan in Synonyms: 771
                                     Tissue  \
0                                     blood
1                                     blood
2                                     blood
3                          pleural effusion
4                               bone marrow
...                                     ...
161650         Adult acute myeloid leukemia
161654  Haematopoietic and lymphoid myeloma
161655                           Fibroblast
161656                         Osteosarcoma
161658                       Mouse leukemia

                                          Synonyms
0       Hel|GM06141|GM06141B|Human ErythroLeukemia
1               HL 60|HL.60|HL60|Human Leukemia-60
2                                             HMC1
3             K562|K.562|K 562|KO|GM05372|GM05372E
4                                        NB-4|NB.4
...                                            ...
161650                                         NaN
161654                                         NaN
161655                                         NaN
161656                                         NaN
161658                                         NaN

[68068 rows x 2 columns]

# keys in Organism: 850
160057
# Nan in Organism: 0
# Nan in Name: 1
                          Organism          Name
0             Homo sapiens (human)           HEL
1             Homo sapiens (human)         HL-60
2             Homo sapiens (human)         HMC-1
3             Homo sapiens (human)         K-562
4             Homo sapiens (human)           NB4
...                            ...           ...
161654        Homo sapiens (human)        SK-007
161655  Mus musculus (house mouse)  NIH-3T3/LISN
161656        Homo sapiens (human)          KHOS
161657        Homo sapiens (human)    MOLM-13-QR
161658  Mus musculus (house mouse)           RN2

[160057 rows x 2 columns]

# keys in Organism: 850
3253
# Nan in Organism: 0
# Nan in Tissue: 254
                          Organism                               Tissue
0             Homo sapiens (human)                                blood
3             Homo sapiens (human)                     pleural effusion
4             Homo sapiens (human)                          bone marrow
16            Homo sapiens (human)                                  NaN
17            Homo sapiens (human)                           cerebellum
...                            ...                                  ...
161650        Homo sapiens (human)         Adult acute myeloid leukemia
161654        Homo sapiens (human)  Haematopoietic and lymphoid myeloma
161655  Mus musculus (house mouse)                           Fibroblast
161656        Homo sapiens (human)                         Osteosarcoma
161658  Mus musculus (house mouse)                       Mouse leukemia

[3253 rows x 2 columns]

# keys in Organism: 850
850
# Nan in Organism: 0
# Nan in TaxonomyID: 0
                                            Organism  TaxonomyID
0                               Homo sapiens (human)      9606.0
49                Chlorocebus sabaeus (green monkey)     60711.0
59                     Neogale vison (American mink)    452646.0
60                        Mus musculus (house mouse)     10090.0
97                    Rattus norvegicus (Norway rat)     10116.0
...                                              ...         ...
159795  Premnas biaculeatus (spinecheek anemonefish)     80991.0
160346      Balaenoptera acutorostrata (minke whale)      9767.0
160353                             Diplothrix legata    106283.0
160537                         Euphractus sexcinctus    143300.0
160693                            Huso huso (beluga)     61971.0

[850 rows x 2 columns]

# keys in Organism: 850
79275
# Nan in Organism: 0
# Nan in Synonyms: 512
                    Organism                                    Synonyms
0       Homo sapiens (human)  Hel|GM06141|GM06141B|Human ErythroLeukemia
1       Homo sapiens (human)          HL 60|HL.60|HL60|Human Leukemia-60
2       Homo sapiens (human)                                        HMC1
3       Homo sapiens (human)        K562|K.562|K 562|KO|GM05372|GM05372E
4       Homo sapiens (human)                                   NB-4|NB.4
...                      ...                                         ...
161636  Homo sapiens (human)                            hiPSC-KCNH2_G53S
161638  Homo sapiens (human)                         hiPSC-KCNQ1_G245G_2
161639  Homo sapiens (human)                         hiPSC-KCNQ1_G245G_1
161640  Homo sapiens (human)                                 JIPSC001334
161641  Homo sapiens (human)                                 JIPSC001314

[79275 rows x 2 columns]

# keys in TaxonomyID: 846
160057
# Nan in TaxonomyID: 0
# Nan in Name: 1
        TaxonomyID          Name
0           9606.0           HEL
1           9606.0         HL-60
2           9606.0         HMC-1
3           9606.0         K-562
4           9606.0           NB4
...            ...           ...
161654      9606.0        SK-007
161655     10090.0  NIH-3T3/LISN
161656      9606.0          KHOS
161657      9606.0    MOLM-13-QR
161658     10090.0           RN2

[160057 rows x 2 columns]

# keys in TaxonomyID: 846
3249
# Nan in TaxonomyID: 0
# Nan in Tissue: 253
        TaxonomyID                               Tissue
0           9606.0                                blood
3           9606.0                     pleural effusion
4           9606.0                          bone marrow
16          9606.0                                  NaN
17          9606.0                           cerebellum
...            ...                                  ...
161650      9606.0         Adult acute myeloid leukemia
161654      9606.0  Haematopoietic and lymphoid myeloma
161655     10090.0                           Fibroblast
161656      9606.0                         Osteosarcoma
161658     10090.0                       Mouse leukemia

[3249 rows x 2 columns]

# keys in TaxonomyID: 846
850
# Nan in TaxonomyID: 0
# Nan in Organism: 0
        TaxonomyID                                      Organism
0           9606.0                          Homo sapiens (human)
49         60711.0            Chlorocebus sabaeus (green monkey)
59        452646.0                 Neogale vison (American mink)
60         10090.0                    Mus musculus (house mouse)
97         10116.0                Rattus norvegicus (Norway rat)
...            ...                                           ...
159795     80991.0  Premnas biaculeatus (spinecheek anemonefish)
160346      9767.0      Balaenoptera acutorostrata (minke whale)
160353    106283.0                             Diplothrix legata
160537    143300.0                         Euphractus sexcinctus
160693     61971.0                            Huso huso (beluga)

[850 rows x 2 columns]

# keys in TaxonomyID: 846
79272
# Nan in TaxonomyID: 0
# Nan in Synonyms: 509
        TaxonomyID                                    Synonyms
0           9606.0  Hel|GM06141|GM06141B|Human ErythroLeukemia
1           9606.0          HL 60|HL.60|HL60|Human Leukemia-60
2           9606.0                                        HMC1
3           9606.0        K562|K.562|K 562|KO|GM05372|GM05372E
4           9606.0                                   NB-4|NB.4
...            ...                                         ...
161636      9606.0                            hiPSC-KCNH2_G53S
161638      9606.0                         hiPSC-KCNQ1_G245G_2
161639      9606.0                         hiPSC-KCNQ1_G245G_1
161640      9606.0                                 JIPSC001334
161641      9606.0                                 JIPSC001314

[79272 rows x 2 columns]

# keys in Synonyms: 79320
79924
# Nan in Synonyms: 0
# Nan in Name: 0
                                          Synonyms  \
0       Hel|GM06141|GM06141B|Human ErythroLeukemia
1               HL 60|HL.60|HL60|Human Leukemia-60
2                                             HMC1
3             K562|K.562|K 562|KO|GM05372|GM05372E
4                                        NB-4|NB.4
...                                            ...
161636                            hiPSC-KCNH2_G53S
161638                         hiPSC-KCNQ1_G245G_2
161639                         hiPSC-KCNQ1_G245G_1
161640                                 JIPSC001334
161641                                 JIPSC001314

                               Name
0                               HEL
1                             HL-60
2                             HMC-1
3                             K-562
4                               NB4
...                             ...
161636                   YUCMi022-A
161638                   YUCMi024-A
161639                   YUCMi025-A
161640  KOLF2.1J RAB39B T168K REV/Y
161641  KOLF2.1J RAB39B T168K SNV/Y

[79924 rows x 2 columns]

# keys in Synonyms: 79320
79499
# Nan in Synonyms: 0
# Nan in Tissue: 12202
                                          Synonyms            Tissue
0       Hel|GM06141|GM06141B|Human ErythroLeukemia             blood
1               HL 60|HL.60|HL60|Human Leukemia-60             blood
2                                             HMC1             blood
3             K562|K.562|K 562|KO|GM05372|GM05372E  pleural effusion
4                                        NB-4|NB.4       bone marrow
...                                            ...               ...
161636                            hiPSC-KCNH2_G53S             blood
161638                         hiPSC-KCNQ1_G245G_2             blood
161639                         hiPSC-KCNQ1_G245G_1             blood
161640                                 JIPSC001334      skin of body
161641                                 JIPSC001314      skin of body

[79499 rows x 2 columns]

# keys in Synonyms: 79320
79451
# Nan in Synonyms: 0
# Nan in Organism: 688
                                          Synonyms              Organism
0       Hel|GM06141|GM06141B|Human ErythroLeukemia  Homo sapiens (human)
1               HL 60|HL.60|HL60|Human Leukemia-60  Homo sapiens (human)
2                                             HMC1  Homo sapiens (human)
3             K562|K.562|K 562|KO|GM05372|GM05372E  Homo sapiens (human)
4                                        NB-4|NB.4  Homo sapiens (human)
...                                            ...                   ...
161636                            hiPSC-KCNH2_G53S  Homo sapiens (human)
161638                         hiPSC-KCNQ1_G245G_2  Homo sapiens (human)
161639                         hiPSC-KCNQ1_G245G_1  Homo sapiens (human)
161640                                 JIPSC001334  Homo sapiens (human)
161641                                 JIPSC001314  Homo sapiens (human)

[79451 rows x 2 columns]

# keys in Synonyms: 79320
79451
# Nan in Synonyms: 0
# Nan in TaxonomyID: 688
                                          Synonyms  TaxonomyID
0       Hel|GM06141|GM06141B|Human ErythroLeukemia      9606.0
1               HL 60|HL.60|HL60|Human Leukemia-60      9606.0
2                                             HMC1      9606.0
3             K562|K.562|K 562|KO|GM05372|GM05372E      9606.0
4                                        NB-4|NB.4      9606.0
...                                            ...         ...
161636                            hiPSC-KCNH2_G53S      9606.0
161638                         hiPSC-KCNQ1_G245G_2      9606.0
161639                         hiPSC-KCNQ1_G245G_1      9606.0
161640                                 JIPSC001334      9606.0
161641                                 JIPSC001314      9606.0

[79451 rows x 2 columns]

In [16]:
taxonomy_ids = df['TaxonomyID'].unique()
len(taxonomy_ids)

847